"""AssetSpec -> TypeScript factory function satisfying the Program ABI (web/src/program_abi.ts).

Deterministic: same spec -> byte-identical source. Naming: part Group is named
``<part_id>``, joint pivot Group is named ``joint:<joint_id>``.
"""
from __future__ import annotations

from turnitover.core.spec import AssetSpec, JointSpec, JointType, PartSpec


def _v(v) -> str:
    return ", ".join(_num(x) for x in v)


def _num(x: float) -> str:
    return repr(float(x)) if not isinstance(x, int) else str(x)


def _sub(a, b):
    return tuple(x - y for x, y in zip(a, b))


def emit_program(spec: AssetSpec) -> str:
    joints_by_part = {j.part: j for j in spec.joints}
    lines: list[str] = []
    w = lines.append
    w("// Generated by turnitover.assets.emit — Program ABI v1")
    w("import type * as THREE_NS from 'three';")
    w("type Three = typeof THREE_NS;")
    w("")
    w("export default function createObject(THREE: Three) {")
    w(f"  const root = new THREE.Group(); root.name = {spec.asset_id!r};")
    w("  const groups: Record<string, THREE_NS.Group> = {};")
    w("  const materials: Record<string, THREE_NS.MeshStandardMaterial> = {};")
    for m in spec.materials:
        w(
            f"  materials[{m.id!r}] = new THREE.MeshStandardMaterial({{ color: {m.color!r}, "
            f"metalness: {_num(m.metalness)}, roughness: {_num(m.roughness)} }});"
        )
    w("  const joints: Record<string, { type: 'revolute' | 'prismatic'; part: string; limits: [number, number]; set(v: number): void }> = {};")
    w("")
    for p in spec.parts:
        _emit_part(w, p, joints_by_part.get(p.id))
    w("")
    for p in spec.parts:
        parent = f"groups[{p.parent!r}]" if p.parent else "root"
        j = joints_by_part.get(p.id)
        if j is None:
            w(f"  {parent}.add(groups[{p.id!r}]);")
        else:
            w(f"  {parent}.add(groups[{'joint:' + j.id!r}]);")
    w("")
    w("  function dispose() {")
    w("    root.traverse((o) => { const m = o as THREE_NS.Mesh; if (m.isMesh) { m.geometry.dispose(); } });")
    w("    for (const k in materials) materials[k].dispose();")
    w("  }")
    w("  return { root, joints, dispose };")
    w("}")
    return "\n".join(lines) + "\n"


def _emit_part(w, p: PartSpec, joint: JointSpec | None) -> None:
    w(f"  {{ // part {p.id}")
    w(f"    const g = new THREE.Group(); g.name = {p.id!r};")
    w(
        f"    const mesh = new THREE.Mesh(new THREE.BoxGeometry({_v(p.size)}, {_v(p.segments)}), "
        f"materials[{p.material!r}]); mesh.name = {p.id + '#mesh'!r};"
    )
    w("    g.add(mesh);")
    if p.rotation != (0.0, 0.0, 0.0):
        w(f"    g.rotation.set({_v(p.rotation)});")
    if joint is None:
        w(f"    g.position.set({_v(p.origin)});")
        w(f"    groups[{p.id!r}] = g;")
    else:
        local = _sub(p.origin, joint.anchor)
        w(f"    g.position.set({_v(local)});")
        w(f"    const pivot = new THREE.Group(); pivot.name = {'joint:' + joint.id!r};")
        w(f"    pivot.position.set({_v(joint.anchor)});")
        w("    pivot.add(g);")
        w(f"    groups[{p.id!r}] = g; groups[{'joint:' + joint.id!r}] = pivot;")
        w(f"    const axis = new THREE.Vector3({_v(joint.axis)}).normalize();")
        w(f"    const limits: [number, number] = [{_num(joint.limits[0])}, {_num(joint.limits[1])}];")
        w(f"    const sign = {_num(joint.sign)};")
        w(f"    const anchor = new THREE.Vector3({_v(joint.anchor)});")
        if joint.type is JointType.REVOLUTE:
            setter = "pivot.quaternion.setFromAxisAngle(axis, sign * v);"
        else:
            setter = "pivot.position.copy(anchor).addScaledVector(axis, sign * v);"
        w(
            f"    joints[{joint.id!r}] = {{ type: {joint.type.value!r}, part: {p.id!r}, limits, "
            f"set(v: number) {{ v = Math.min(limits[1], Math.max(limits[0], v)); {setter} }} }};"
        )
    w("  }")
