// Generated by turnitover.assets.emit — Program ABI v1
import type * as THREE_NS from 'three';
type Three = typeof THREE_NS;

export default function createObject(THREE: Three) {
  const root = new THREE.Group(); root.name = 'toy_cabinet';
  const groups: Record<string, THREE_NS.Group> = {};
  const materials: Record<string, THREE_NS.MeshStandardMaterial> = {};
  materials['body'] = new THREE.MeshStandardMaterial({ color: '#b08a5a', metalness: 0.0, roughness: 0.7 });
  materials['drawer'] = new THREE.MeshStandardMaterial({ color: '#5a7fb0', metalness: 0.0, roughness: 0.6 });
  materials['door'] = new THREE.MeshStandardMaterial({ color: '#8a5a5a', metalness: 0.0, roughness: 0.6 });
  const joints: Record<string, { type: 'revolute' | 'prismatic'; part: string; limits: [number, number]; set(v: number): void }> = {};

  { // part body_back
    const g = new THREE.Group(); g.name = 'body_back';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.8, 0.02, 1, 1, 1), materials['body']); mesh.name = 'body_back#mesh';
    g.add(mesh);
    g.position.set(0.0, 0.4, -0.24);
    groups['body_back'] = g;
  }
  { // part body_left
    const g = new THREE.Group(); g.name = 'body_left';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.02, 0.8, 0.5, 1, 1, 1), materials['body']); mesh.name = 'body_left#mesh';
    g.add(mesh);
    g.position.set(-0.29, 0.4, 0.0);
    groups['body_left'] = g;
  }
  { // part body_right
    const g = new THREE.Group(); g.name = 'body_right';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.02, 0.8, 0.5, 1, 1, 1), materials['body']); mesh.name = 'body_right#mesh';
    g.add(mesh);
    g.position.set(0.29, 0.4, 0.0);
    groups['body_right'] = g;
  }
  { // part body_top
    const g = new THREE.Group(); g.name = 'body_top';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.02, 0.5, 1, 1, 1), materials['body']); mesh.name = 'body_top#mesh';
    g.add(mesh);
    g.position.set(0.0, 0.79, 0.0);
    groups['body_top'] = g;
  }
  { // part body_bottom
    const g = new THREE.Group(); g.name = 'body_bottom';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.6, 0.02, 0.5, 1, 1, 1), materials['body']); mesh.name = 'body_bottom#mesh';
    g.add(mesh);
    g.position.set(0.0, 0.01, 0.0);
    groups['body_bottom'] = g;
  }
  { // part body_shelf
    const g = new THREE.Group(); g.name = 'body_shelf';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5599999999999999, 0.02, 0.48, 1, 1, 1), materials['body']); mesh.name = 'body_shelf#mesh';
    g.add(mesh);
    g.position.set(0.0, 0.4, 0.0);
    groups['body_shelf'] = g;
  }
  { // part drawer_0
    const g = new THREE.Group(); g.name = 'drawer_0';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5499999999999999, 0.18000000000000002, 0.47, 16, 16, 16), materials['drawer']); mesh.name = 'drawer_0#mesh';
    g.add(mesh);
    g.position.set(0.0, 0.0, 0.0);
    const pivot = new THREE.Group(); pivot.name = 'joint:drawer_0';
    pivot.position.set(0.0, 0.12000000000000001, 0.0);
    pivot.add(g);
    groups['drawer_0'] = g; groups['joint:drawer_0'] = pivot;
    const axis = new THREE.Vector3(0.0, 0.0, 1.0).normalize();
    const limits: [number, number] = [0.0, 0.35];
    const sign = 1.0;
    const anchor = new THREE.Vector3(0.0, 0.12000000000000001, 0.0);
    joints['drawer_0'] = { type: 'prismatic', part: 'drawer_0', limits, set(v: number) { v = Math.min(limits[1], Math.max(limits[0], v)); pivot.position.copy(anchor).addScaledVector(axis, sign * v); } };
  }
  { // part drawer_1
    const g = new THREE.Group(); g.name = 'drawer_1';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5499999999999999, 0.18000000000000002, 0.47, 16, 16, 16), materials['drawer']); mesh.name = 'drawer_1#mesh';
    g.add(mesh);
    g.position.set(0.0, 0.0, 0.0);
    const pivot = new THREE.Group(); pivot.name = 'joint:drawer_1';
    pivot.position.set(0.0, 0.32, 0.0);
    pivot.add(g);
    groups['drawer_1'] = g; groups['joint:drawer_1'] = pivot;
    const axis = new THREE.Vector3(0.0, 0.0, 1.0).normalize();
    const limits: [number, number] = [0.0, 0.35];
    const sign = 1.0;
    const anchor = new THREE.Vector3(0.0, 0.32, 0.0);
    joints['drawer_1'] = { type: 'prismatic', part: 'drawer_1', limits, set(v: number) { v = Math.min(limits[1], Math.max(limits[0], v)); pivot.position.copy(anchor).addScaledVector(axis, sign * v); } };
  }
  { // part door
    const g = new THREE.Group(); g.name = 'door';
    const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5499999999999999, 0.37, 0.02, 1, 1, 1), materials['door']); mesh.name = 'door#mesh';
    g.add(mesh);
    g.position.set(0.27999999999999997, 0.0, 0.0);
    const pivot = new THREE.Group(); pivot.name = 'joint:door';
    pivot.position.set(-0.27999999999999997, 0.6000000000000001, 0.24);
    pivot.add(g);
    groups['door'] = g; groups['joint:door'] = pivot;
    const axis = new THREE.Vector3(0.0, 1.0, 0.0).normalize();
    const limits: [number, number] = [0.0, 1.5707963267948966];
    const sign = -1.0;
    const anchor = new THREE.Vector3(-0.27999999999999997, 0.6000000000000001, 0.24);
    joints['door'] = { type: 'revolute', part: 'door', limits, set(v: number) { v = Math.min(limits[1], Math.max(limits[0], v)); pivot.quaternion.setFromAxisAngle(axis, sign * v); } };
  }

  root.add(groups['body_back']);
  root.add(groups['body_left']);
  root.add(groups['body_right']);
  root.add(groups['body_top']);
  root.add(groups['body_bottom']);
  root.add(groups['body_shelf']);
  root.add(groups['joint:drawer_0']);
  root.add(groups['joint:drawer_1']);
  root.add(groups['joint:door']);

  function dispose() {
    root.traverse((o) => { const m = o as THREE_NS.Mesh; if (m.isMesh) { m.geometry.dispose(); } });
    for (const k in materials) materials[k].dispose();
  }
  return { root, joints, dispose };
}
